### ISSUE TITLE
Build failure with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Sp1l** [lumina-desktop/lumina#555]
I've done an exp-run with [OpenSSL 1.1.1.p2](/Sp1l/ports/tree/master/security/openssl-master) on FreeBSD 11.1 amd64 and ran into a [build failure (poudriere log)](https://keg.brnrd.eu/data/111amd64-default-openssl111/2018-03-11_11h02m59s/logs/errors/lumina-core-1.4.1.log) in x11/lumina-core.

```
desktop-plugins/rssreader/RSSObjects.cpp:348:17: error: member access into incomplete type 'const QSslError'
    if(errors[i].error()==QSslError::SelfSignedCertificate || errors[i].error()==QSslError::SelfSignedCertificateInChain){ ok++; }
                ^
/usr/local/include/qt5/QtNetwork/qnetworkaccessmanager.h:64:7: note: forward declaration of 'QSslError'
class QSslError;
      ^
desktop-plugins/rssreader/RSSObjects.cpp:349:58: error: member access into incomplete type 'const QSslError'
    else{ qDebug() << "Unhandled SSL Error:" << errors[i].errorString(); }
                                                         ^
/usr/local/include/qt5/QtNetwork/qnetworkaccessmanager.h:64:7: note: forward declaration of 'QSslError'
class QSslError;
      ^
```

qt5-network has issues with 1.1.0/1.1.1 that I need to fix in my tree.

**Comment by Sp1l** [comment]
Looks like a missing dependency on qt5-network to me (which fails to build with OpenSSL 1.1)

**Comment by beanpole135** [comment]
Could you please double-check which version of the Lumina port you are building?
According to [Freshports](https://www.freshports.org/x11/lumina-core/), the x11/lumina-core port (version 1.4.1) has a stated library dependency on the net/qt5-network port. This seems to indicate that the port is accurately listing it's dependencies, but that your poudriere session did not see/verify that dependency first.

**Comment by lbartoletti** [comment]
There is a lot of error with openssl 1.1. You need to take a look at bugs.freebsd.org, for example for qt5-network https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233197

**Comment by beanpole135** [comment]
Lumina and qt5-network are building/running fine with OpenSSL 1.1.1 in some of the latest builds by Project Trident.
Closing issue as it seems like it was resolved upstream by the Qt porting team for FreeBSD.
